version: "3.9"

services:
  hugo:
    image: hugomods/hugo:0.136.5 # extended build, Sass, PostCSS, etc.
    command: >
      hugo server -D --bind 0.0.0.0
      --baseURL http://localhost:1313
    ports:
      - "1313:1313"
    volumes:
      - .:/src # live-reload works through the mount
    environment:
      - HUGO_ENVIRONMENT=development
